apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: retool-staging-api
  name: retool-staging-api
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: retool-staging-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: retool-staging-api
    spec:
      containers:
      - args:
        - bash
        - -c
        - ./docker_scripts/wait-for-it.sh -t 0 $POSTGRES_HOST:$POSTGRES_PORT;
          ./docker_scripts/start_api.sh
        env:
        - name: BASE_DOMAIN
          value: "https://retool-staging.treasurefinancial.com"
        - name: RESTRICTED_DOMAIN
          # matches the Google business account not the company URI
          value: "treasure.tech"
        - name: COOKIE_INSECURE
          value: "false"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: retoolstagingsecrets
              key: jwt_secret
        - name: SERVICE_TYPE
          value: MAIN_BACKEND,DB_CONNECTOR,DB_SSH_CONNECTOR
        - name: NODE_ENV
          value: production
        - name: POSTGRES_DB
          value: "retool"
        - name: POSTGRES_HOST
          value: 127.0.0.1 # loopback because of cloud-sql-proxy
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "retool"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: retoolstagingsecrets
              key: postgres_password
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: retoolstagingsecrets
              key: encryption_key
        - name: LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: retoolstagingsecrets
              key: license_key
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: retoolstagingsecrets
              key: google_client_id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: retoolstagingsecrets
              key: google_client_secret
        - name: GITHUB_APP_ID
          value: "154266"
        - name: GITHUB_APP_INSTALLATION_ID
          value: "20910151"
        - name: GITHUB_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: retoolstagingsecrets
              key: github_app_private_key
        image: tryretool/backend:2.110.2
        name: retool-staging-api
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "2.5Gi"
            cpu: "1"
          requests:
            memory: "1.5Gi"
            cpu: "1"
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.30.0
        imagePullPolicy: IfNotPresent
        command: ["/cloud_sql_proxy",
          "-instances=tn-mvp-staging:us-central1:staging-upgraded=tcp:5432" ]
        securityContext:
            runAsNonRoot: true
            runAsUser: 65532
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
      # any node pools that schedule this job must have workload-identity properly configured
      serviceAccount: workload-identity-ksa
      serviceAccountName: workload-identity-ksa
      restartPolicy: Always

status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: retool-staging-api
  name: retool-staging-api
spec:
  type: LoadBalancer
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: retool-staging-api
status:
  loadBalancer: {}
