apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: jobs-runner
  name: jobs-runner
spec:
  replicas: 1 # jobs-runner pod should never be more than 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: jobs-runner
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jobs-runner
    spec:
      containers:
      - args:
        - bash
        - -c
        - ./docker_scripts/wait-for-it.sh -t 0 $POSTGRES_HOST:$POSTGRES_PORT;
          ./docker_scripts/start_api.sh
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: jwt_secret
        - name: SERVICE_TYPE
          value: JOBS_RUNNER
        - name: NODE_ENV
          value: production
        - name: POSTGRES_DB
          value: "retool_prod"
        - name: POSTGRES_HOST
          value: 127.0.0.1
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "retool-prod"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: postgres_password
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: encryption_key
        - name: LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: license_key
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: google_client_id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: google_client_secret
        - name: GITHUB_APP_ID
          value: "154266"
        - name: GITHUB_APP_INSTALLATION_ID
          value: "20910151"
        - name: GITHUB_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: retoolsecrets
              key: github_app_private_key
        - name: LOG_LEVEL  # debugging
          value: "verbose"
        image: tryretool/backend:2.103.4
        name: jobs-runner
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
          requests:
            cpu: "250m"
            memory: "1Gi"
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.30.0
        imagePullPolicy: IfNotPresent
        command: ["/cloud_sql_proxy",
          "-instances=treasure-production:us-west1:treasure-production=tcp:5432" ]
        securityContext:
            runAsNonRoot: true
            runAsUser: 65532
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
      serviceAccount: workload-identity
      serviceAccountName: workload-identity
      restartPolicy: Always
status: {}
